
baseurl = "https://ar.simeononsecurity.ch"
languageCode = "ar"
defaultContentLanguage = "ar"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
    'pl',
]