
baseurl = "https://ja.simeononsecurity.com"
languageCode = "ja"
defaultContentLanguage = "ja"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
    'pl',
]
