baseurl = "https://ar.simeononsecurity.ch"
defaultContentLanguage = "ar"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]
[languages]
[languages.ar]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.ar.xml" }]
languageName = 'العربية'
# languageCode = "ar"
weight = 5
title = "simeononsecurity"
subtitle = "الأمن السيبراني، الإدارة، العملات الرقمية"
description = "ابقى على اطلاع في مجال الأمن السيبراني. استكشف آخر الاتجاهات والممارسات الأمنية والتكنولوجية على SimeonOnSecurity.ch. مورد مهم للجميع."
keywords = "أمن، خصوصية، إدارة، أمن سيبراني، تكنولوجيا المعلومات، العملات الرقمية، مدونة، التصلب، التقدير، الامتثال، البرمجة، ديف أوبس، باور شيل، سي شارب، أنسيبل، دوكر كونتينر، ويندوز، الجريمة الرقمية و التحقيق، المختبر المنزلي، حلول الشركات الناشئة، بايثون، ويندوز 10"
copyright = "SimeonOnSecurity"
menuMore = "المزيد"
writtenBy = "المؤلف:"
readMore = "اقرأ المزيد"
readOtherPosts = "اقرأ المزيد"
newerPosts = "أحدث المقالات"
olderPosts = "المقالات السابقة"
minuteReadingTime = "دقيقة واحدة للقراءة"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "تم التعديل في:"

[languages.ar.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.ar.menu]
[[languages.ar.menu.main]]
identifier = "Articles"
name = "المقالات"
url = "/articles"
[[languages.ar.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.ar.menu.main]]
identifier = "TIL"
name = "ما تعلمته اليوم"
url = "/til"
[[languages.ar.menu.main]]
identifier = "Writeups"
name = "كتابات"
url = "/writeups"
[[languages.ar.menu.main]]
identifier = "Recommendations"
name = "التوصيات"
url = "/recommendations"