languageCode = "en-us"
title = "simeononsecurity"
theme = "soshellofriend"
baseurl = "https://simeononsecurity.ch"
paginate = 5
canonifyURLs = true
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
relativeURLs = true
enableGitInfo = true
refLinksNotFoundURL = "simeononsecurity.ch"
#disqusShortname = "simeononsecurity"

[Author]
name = "SimeonOnSecurity"

[params]
#Google Analytics Tag
googleAnalytics = "UA-173461240-1"

#Site Post Cover
images = ["/img/banner.png"]

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "articles"
contentdir = "content"

# "light" or "dark"
defaultTheme = "dark"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 0

# Show reading time in minutes for posts
#showReadingTime = true

# Show table of contents at the top of your posts (defaults to false)
# Alternatively, add this param to post front matter for specific posts
#toc = true

# Show full page content in RSS feed items
#(default is Description or Summary metadata in the front matter)
rssFullText = false

logo = "/img/favicon.png"
copyright = "SimeonOnSecurity"

# Default AMP components for the whole site
ampElements = [
        "amp-analytics",
        "amp-social-share",
        "amp-install-serviceworker",
        "amp-iframe",
]

# Google Analytics code

# Adsense publisher code
adsensePublisher = "ca-pub-4092442123207538"

# Social sites for metatags
facebookSite = ""
twitterSite = "@simeonsecurity"

# Structured data elements
socialProfiles = [
        "https://twitter.com/simeonsecurity",
        "https://github.com/simeononsecurity",
]

alternatePageName = "SimeonOnSecurity"
organizationLogo = "/img/banner.png"
organizationName = "SimeonOnSecurity"

publisherName = "SimeonOnSecurity"
publisherLogo = "/img/banner.png"
publisherLogoWidth = 460
publisherLogoHeight = 460


[languages]
[languages.en]
title = "simeononsecurity"
subtitle = "a cybersecurity, automation, information technology, and cryptocurrency blog"
description = "SimeonOnSecurity.ch is a comprehensive blog that covers a wide range of topics related to privacy, security, and technology. From programming and devops to automation and PowerShell, this blog offers in-depth information and guidance on the latest trends and best practices in cybersecurity. Whether you're a home lab enthusiast or an enterprise solution provider, this blog is an essential resource for anyone looking to stay ahead of the curve and protect their digital assets."
keywords = "security, privacy, automation, cybersecurity, information technology, cryptocurrency, blog, hardening, compliance, programming, devops, powershell, c sharp, ansible, docker containers, windows, DoD and DISA STIGs, home labs, enterprise solutions, python, windows 10"
copyright = ""
menuMore = "Show more"
writtenBy = "Written by"
readMore = "Learn more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "Modified:"

[languages.en.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "Articles"
name = "Articles"
url = "/articles"
[[languages.en.menu.main]]
identifier = "Blog"
name = "Blog"
url = "/blog"
[[languages.en.menu.main]]
identifier = "CTF Rankings"
name = "CTF Rankings"
url = "/ctfranks"
[[languages.en.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.en.menu.main]]
identifier = "Guides"
name = "Guides"
url = "/guides"
[[languages.en.menu.main]]
identifier = "TIL"
name = "Today I Learned"
url = "/til"
[[languages.en.menu.main]]
identifier = "Writeups"
name = "Writeups"
url = "/writeups"
[[languages.en.menu.main]]
identifier = "Recommendations"
name = "Recommendations"
url = "/recommendhome"
[[languages.en.menu.main]]
identifier = "About"
name = "About"
url = "/about"
#  [[languages.en.menu.main]]
#    identifier = "showcase"
#    name = "Showcase"
#    url = "/showcase"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 1

[security]
enableInlineShortcodes = true
[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
[security.funcs]
getenv = ['^HUGO_', '^WC_', 'babel']
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']


[imaging]
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    includeFields = ''

