baseurl = "https:/ru.simeononsecurity.ch"
defaultContentLanguage = "ru"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
]
[languages]
[languages.ru]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.ru.xml" }]
languageName = "Русский"
# languageCode = "ru"
weight = 20
title = "SimeonOnSecurity"
subtitle = "Кибербезопасность, автоматизация и шифрование"
description = "Будьте в курсе последних разработок в области кибербезопасности. Получайте последние новости и лучшие практики в области конфиденциальности, безопасности и технологий на сайте SimeonOnSecurity.ch. Ценный ресурс для всех."
keywords = "безопасность, конфиденциальность, автоматизация, кибербезопасность, информационные технологии, криптовалюты, блог, непрерывное совершенствование, программирование, DevOps, PowerShell, C#, Ansible, контейнеры Docker, Windows, DoD и SST, домашняя лаборатория, решение проблем ядра, Python, Windows 10"
copyright = "SimeonOnSecurity"
menuMore = "Еще"
writtenBy = "Написано"
readMore = "Читать далее"
readOtherPosts = "Читать другие статьи"
newerPosts = "Новые статьи"
olderPosts = "Старые статьи"
minuteReadingTime = "минут на чтение"
dateFormatSingle = "02.01.2006"
dateFormatList = "02.01.2006"
enableRobotsTXT = "true"
lastModDisplay = "Последнее обновление:"

[languages.ru.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.ru.menu]
[[languages.ru.menu.main]]
identifier = "Статьи"
name = "Статьи"
url = "/articles"
[[languages.ru.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.ru.menu.main]]
identifier = "TIL"
name = "Сегодня я узнал"
url = "/til"
[[languages.ru.menu.main]]
identifier = "Письмо"
name = "Письмо"
url = "/writeups"
[[languages.ru.menu.main]]
identifier = "Рекомендации"
name = "Рекомендации"
url = "/recommendations"