baseurl = "https://bn.simeononsecurity.ch"
defaultContentLanguage = "bn"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]
[languages]
[languages.bn]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.bn.xml" }]
languageName = "বাংলা"
# languageCode = "bn"
weight = 7
title = "সিমিয়ন অন সিকিউরিটি"
subtitle = "সাইবার নিরাপত্তা, অটোমেশন, ক্রিপ্টো"
description = "সাইবার নিরাপত্তার উন্নয়নে আপডেটে থাকুন। প্রাইভেসি, নিরাপত্তা এবং প্রযুক্তিতে সর্বশেষ প্রবন্ধ এবং সেরা প্র্যাকটিস সম্পর্কে জানুন SimeonOnSecurity.ch এ। সকলের জন্য একটি গুরুত্বপূর্ণ সম্পদ।"
keywords = "নিরাপত্তা, প্রাইভেসি, অটোমেশন, সাইবার নিরাপত্তা, তথ্য প্রযুক্তি, ক্রিপ্টোকারেন্সি, ব্লগ, কঠোরতার উন্নয়ন, সম্পূর্ণতা, প্রোগ্রামিং, ডেভঅপস, পাওয়ারশেল, সি শার্প, এ্যানসিবল, ডকার কন্টেইনার, উইন্ডোজ, ডিওডি এবং ডিসা এসটিআইজি, বাড়িতে ল্যাব, কর্নেল সমস্যা সমাধান, পাইথন, উইন্ডোজ 10"
copyright = "SimeonOnSecurity"
menuMore = "আরও"
writtenBy = "লেখা"
readMore = "আরও পড়ুন"
readOtherPosts = "অন্যান্য পোস্ট পড়ুন"
newerPosts = "নতুন পোস্ট"
olderPosts = "পুরানো পোস্ট"
minuteReadingTime = "মিনিটের পঠন সময়"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
lastModDisplay = "সর্বশেষ পরিবর্তন:"

[languages.bn.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.bn.menu]
[[languages.bn.menu.main]]
identifier = "পোস্ট"
name = "পোস্ট"
url = "/articles"
[[languages.bn.menu.main]]
identifier = "GitHub"
name = "গিটহাব"
url = "/github"
[[languages.bn.menu.main]]
identifier = "টিআইএল"
name = "আজ শিখলাম"
url = "/til"
[[languages.bn.menu.main]]
identifier = "লিখন"
name = "লিখন"
url = "/writeups"
[[languages.bn.menu.main]]
identifier = "সুপারিশ"
name = "সুপারিশ"
url = "/recommendations"
