title = "simeononsecurity"
theme = "soshellofriend"
#baseurl = "https://simeononsecurity.ch"
paginate = 5
canonifyURLs = true
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
relativeURLs = true
enableGitInfo = true
refLinksNotFoundURL = "simeononsecurity.ch"
#disqusShortname = "simeononsecurity"
author = "SimeonOnSecurity"

[Author]
name = "SimeonOnSecurity"

[params]
enableMissingTranslationPlaceholders = true

#Google Analytics Tag
googleAnalytics = "G-W3SL745QY6"

#Site Post Cover
images = ["/img/banner.png"]
logo = "/img/banner.png"
rssImage = "/img/banner.png"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "articles"
contentdir = "content"

# "light" or "dark"
defaultTheme = "dark"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 0

# Show reading time in minutes for posts
#showReadingTime = true

# Show table of contents at the top of your posts (defaults to false)
# Alternatively, add this param to post front matter for specific posts
#toc = true

# Show full page content in RSS feed items
#(default is Description or Summary metadata in the front matter)
rssFullText = false

# Default AMP components for the whole site
ampElements = [
  "amp-analytics",
  "amp-social-share",
  "amp-install-serviceworker",
  "amp-iframe",
]

# Google Analytics code

# Adsense publisher code
adsensePublisher = "ca-pub-4092442123207538"

# Social sites for metatags
facebookSite = ""
twitterSite = "@simeonsecurity"

# Structured data elements
socialProfiles = [
  "https://twitter.com/simeonsecurity",
  "https://github.com/simeononsecurity",
]

alternatePageName = "SimeonOnSecurity"
organizationLogo = "/img/banner.png"
organizationName = "SimeonOnSecurity"

publisherName = "SimeonOnSecurity"
publisherLogo = "/img/banner.png"
publisherLogoWidth = 460
publisherLogoHeight = 460

[logo]
logoText = "simeononsecurity"
logoHomeLink = "/"


[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 1

[security]
enableInlineShortcodes = true
[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
[security.funcs]
getenv = ['^HUGO_', '^WC_', 'babel']
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']

[imaging]
[imaging.exif]
disableDate = true
disableLatLong = true
includeFields = ''

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]
page = ["HTML"]
imageFormats = ["jpg", "png", "webp"]
sitemap = [ "Sitemap" ]
[outputs.imageSizes]
cover = [731, 1054, 1462]
[outputFormats.SITEMAP]
    mediatype = "application/xml"
    baseName = "sitemap"

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["xml"]

[outputFormats]
[outputFormats.FEED]
mediatype = "application/rss"
baseName = "feed"