baseurl = "https://simeononsecurity.ch"
#defaultContentLanguage = "en"
disableLanguages = [
    'fr',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]

[languages]
[languages.en]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.en.xml" }]
languageName = 'English'
#languageCode = "en"
weight = 1
title = "simeononsecurity"
subtitle = "CyberSecurity, Automation, Crypto"
#description = "SimeonOnSecurity.ch is a comprehensive blog that covers a wide range of topics related to privacy, security, and technology. From programming and devops to automation and PowerShell, this blog offers in-depth information and guidance on the latest trends and best practices in cybersecurity. Whether you're a home lab enthusiast or an enterprise solution provider, this blog is an essential resource for anyone looking to stay ahead of the curve and protect their digital assets."
description = "Stay ahead in cybersecurity. Discover latest trends & best practices on privacy, security & tech on SimeonOnSecurity.ch. Essential resource for all."
keywords = "security, privacy, automation, cybersecurity, information technology, cryptocurrency, blog, hardening, compliance, programming, devops, powershell, c sharp, ansible, docker containers, windows, DoD and DISA STIGs, home labs, enterprise solutions, python, windows 10"
copyright = "SimeonOnSecurity"
menuMore = "Show more"
writtenBy = "Written by"
readMore = "Learn more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "Modified:"

[languages.en.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "Articles"
name = "Articles"
url = "/articles"
[[languages.en.menu.main]]
identifier = "Blog"
name = "Blog"
url = "/blog"
[[languages.en.menu.main]]
identifier = "CTF Rankings"
name = "CTF Rankings"
url = "/ctfranks"
[[languages.en.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.en.menu.main]]
identifier = "Guides"
name = "Guides"
url = "/guides"
[[languages.en.menu.main]]
identifier = "TIL"
name = "Today I Learned"
url = "/til"
[[languages.en.menu.main]]
identifier = "Writeups"
name = "Writeups"
url = "/writeups"
[[languages.en.menu.main]]
identifier = "Recommendations"
name = "Recommendations"
url = "/recommendhome"
[[languages.en.menu.main]]
identifier = "About"
name = "About"
url = "/about"