baseurl = "https://hi.simeononsecurity.ch"
defaultContentLanguage = "hi"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]
[languages]
[languages.hi]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.hi.xml" }]
languageName = 'हिन्दी'
# languageCode = "hi"
weight = 4
title = "simeononsecurity"
subtitle = "साइबर सुरक्षा, स्वचालन, क्रिप्टो"
description = "साइबर सुरक्षा में आगे रहें। SimeonOnSecurity.ch पर गोपनीयता, सुरक्षा और तकनीक के नवीनतम रुझानों और सर्वोत्तम अभ्यासों की खोज करें। सभी के लिए एक महत्वपूर्ण संसाधन।"
keywords = "सुरक्षा, गोपनीयता, स्वचालन, साइबर सुरक्षा, सूचना प्रौद्योगिकी, क्रिप्टोकरेंसी, ब्लॉग, हार्डनिंग, अनुमानित करना, पालन करना, प्रोग्रामिंग, डेवओप्स, पावरशेल, सी शार्प, एंसिबल, डॉकर कंटेनर, विंडोज, डीओडी और डिसा स्टिग, होम लैब, उद्यम समाधान, पायथन, विंडोज 10"
copyright = "SimeonOnSecurity"
menuMore = "अधिक दिखाएं"
writtenBy = "लेखक :"
readMore = "अधिक जानें"
readOtherPosts = "अन्य लेख पढ़ें"
newerPosts = "नए लेख"
olderPosts = "पुराने लेख"
minuteReadingTime = "मिनट पढ़ने का समय"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "संशोधित:"

[languages.hi.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.hi.menu]
[[languages.hi.menu.main]]
identifier = "Articles"
name = "लेख"
url = "/articles"
[[languages.hi.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.hi.menu.main]]
identifier = "TIL"
name = "आज मैंने सीखा"
url = "/til"
[[languages.hi.menu.main]]
identifier = "Writeups"
name = "व्राइटअप्स"
url = "/writeups"
[[languages.hi.menu.main]]
identifier = "Recommendations"
name = "सिफारिशें"
url = "/recommendations"