baseurl = "https://ja.simeononsecurity.ch"
defaultContentLanguage = "ja"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]
[languages]
[languages.ja]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.ja.xml" }]
languageName = "日本語"
# languageCode = "ja"
weight = 9
title = "SimeonOnSecurity"
subtitle = "サイバーセキュリティ、自動化、暗号化について"
description = "サイバーセキュリティの最新情報やプライバシー、セキュリティ、技術に関するベストプラクティスをSimeonOnSecurity.chで入手してください。誰でも価値のあるリソースです。"
keywords = "セキュリティ、プライバシー、自動化、サイバーセキュリティ、情報技術、暗号通貨、ブログ、持続的改善、プログラミング、DevOps、PowerShell、C#、Ansible、Dockerコンテナ、Windows、DoDとSST、自宅のラボ、カーネルトラブルシューティング、Python、Windows 10"
copyright = "SimeonOnSecurity"
menuMore = "もっと"
writtenBy = "著者:"
readMore = "続きを読む"
readOtherPosts = "他の投稿を読む"
newerPosts = "新しい投稿"
olderPosts = "古い投稿"
minuteReadingTime = "読了時間"
dateFormatSingle = "2006年1月2日"
dateFormatList = "2006年1月2日"
enableRobotsTXT = "true"
lastModDisplay = "最終更新日:"

[languages.ja.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.ja.menu]
[[languages.ja.menu.main]]
identifier = "Articles"
name = "記事"
url = "/articles"
[[languages.ja.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.ja.menu.main]]
identifier = "TIL"
name = "Today I Learned"
url = "/til"
[[languages.ja.menu.main]]
identifier = "Writing"
name = "執筆"
url = "/writeups"
[[languages.ja.menu.main]]
identifier = "Recommendations"
name = "おすすめ"
url = "/recommendations"