languageCode = "en-us"
title = "simeononsecurity"
theme = "soshellofriend"
# baseurl = "https://simeononsecurity.ch"
paginate = 5
canonifyURLs = true
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
relativeURLs = true
enableGitInfo = true
refLinksNotFoundURL = "simeononsecurity.ch"
#disqusShortname = "simeononsecurity"
author = "SimeonOnSecurity"
defaultContentLanguage = "en"


[Author]
name = "SimeonOnSecurity"

[params]
enableMissingTranslationPlaceholders = true

#Google Analytics Tag
googleAnalytics = "G-W3SL745QY6"

#Site Post Cover
images = ["/img/banner.png"]
logo = "/img/banner.png"
rssImage = "/img/banner.png"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "articles"
contentdir = "content"

# "light" or "dark"
defaultTheme = "dark"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 0

# Show reading time in minutes for posts
#showReadingTime = true

# Show table of contents at the top of your posts (defaults to false)
# Alternatively, add this param to post front matter for specific posts
#toc = true

# Show full page content in RSS feed items
#(default is Description or Summary metadata in the front matter)
rssFullText = false

# Default AMP components for the whole site
ampElements = [
  "amp-analytics",
  "amp-social-share",
  "amp-install-serviceworker",
  "amp-iframe",
]

# Google Analytics code

# Adsense publisher code
adsensePublisher = "ca-pub-4092442123207538"

# Social sites for metatags
facebookSite = ""
twitterSite = "@simeonsecurity"

# Structured data elements
socialProfiles = [
  "https://twitter.com/simeonsecurity",
  "https://github.com/simeononsecurity",
]

alternatePageName = "SimeonOnSecurity"
organizationLogo = "/img/banner.png"
organizationName = "SimeonOnSecurity"

publisherName = "SimeonOnSecurity"
publisherLogo = "/img/banner.png"
publisherLogoWidth = 460
publisherLogoHeight = 460


# [sitemap]
# changefreq = "daily"
# filename = "sitemap.xml"
# priority = 1

[security]
enableInlineShortcodes = true
[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
[security.funcs]
getenv = ['^HUGO_', '^WC_', 'babel']
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']

[imaging]
[imaging.exif]
disableDate = true
disableLatLong = true
includeFields = ''

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]
page = ["HTML"]
imageFormats = ["jpg", "png", "webp"]
sitemap = [ "Sitemap" ]
[outputs.imageSizes]
cover = [731, 1054, 1462]
[outputFormats.SITEMAP]
    mediatype = "application/xml"
    baseName = "sitemap"



[languages]
[languages.en]
baseurl = "https://simeononsecurity.ch"
sitemap = [{ filename = "sitemap.xml" },      { filename = "sitemap.en.xml" },    ]
languageName = 'English'
languageCode = "en"
weight = 1
title = "simeononsecurity"
subtitle = "CyberSecurity, Automation, Crypto"
#description = "SimeonOnSecurity.ch is a comprehensive blog that covers a wide range of topics related to privacy, security, and technology. From programming and devops to automation and PowerShell, this blog offers in-depth information and guidance on the latest trends and best practices in cybersecurity. Whether you're a home lab enthusiast or an enterprise solution provider, this blog is an essential resource for anyone looking to stay ahead of the curve and protect their digital assets."
description = "Stay ahead in cybersecurity. Discover latest trends & best practices on privacy, security & tech on SimeonOnSecurity.ch. Essential resource for all."
keywords = "security, privacy, automation, cybersecurity, information technology, cryptocurrency, blog, hardening, compliance, programming, devops, powershell, c sharp, ansible, docker containers, windows, DoD and DISA STIGs, home labs, enterprise solutions, python, windows 10"
copyright = "SimeonOnSecurity"
menuMore = "Show more"
writtenBy = "Written by"
readMore = "Learn more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "Modified:"

[languages.en.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "Articles"
name = "Articles"
url = "/articles"
[[languages.en.menu.main]]
identifier = "Blog"
name = "Blog"
url = "/blog"
[[languages.en.menu.main]]
identifier = "CTF Rankings"
name = "CTF Rankings"
url = "/ctfranks"
[[languages.en.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.en.menu.main]]
identifier = "Guides"
name = "Guides"
url = "/guides"
[[languages.en.menu.main]]
identifier = "TIL"
name = "Today I Learned"
url = "/til"
[[languages.en.menu.main]]
identifier = "Writeups"
name = "Writeups"
url = "/writeups"
[[languages.en.menu.main]]
identifier = "Recommendations"
name = "Recommendations"
url = "/recommendhome"
[[languages.en.menu.main]]
identifier = "About"
name = "About"
url = "/about"

[languages.es]
baseurl = "https://es.simeononsecurity.ch"
sitemap = { filename = "sitemap.es.xml" }
languageName = "Español"
languageCode = "es"
weight = 2
title = "simeononsecurity"
subtitle = "Ciberseguridad, Automatización, Cripto"
description = "Manténgase a la vanguardia de la ciberseguridad. Descubra las últimas tendencias y las mejores prácticas en privacidad, seguridad y tecnología en SimeonOnSecurity.ch. Un recurso esencial para todos."
keywords = "seguridad, privacidad, automatización, ciberseguridad, tecnología de la información, criptomonedas, blog, endurecimiento, cumplimiento, programación, devops, PowerShell, C sharp, Ansible, contenedores Docker, Windows, DoD y DISA STIGs, laboratorios en casa, soluciones empresariales, Python, Windows 10"
copyright = "SimeonOnSecurity"
menuMore = "Más"
writtenBy = "Escrito por"
readMore = "Leer más"
readOtherPosts = "Leer otros artículos"
newerPosts = "Artículos más nuevos"
olderPosts = "Artículos más antiguos"
minuteReadingTime = "min de lectura"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "Modificado:"

[languages.es.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.es.menu]
[[languages.es.menu.main]]
identifier = "Artículos"
name = "Artículos"
url = "/articles"
[[languages.es.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.es.menu.main]]
identifier = "TIL"
name = "Hoy Aprendí"
url = "/til"
[[languages.es.menu.main]]
identifier = "Writeups"
name = "Writeups"
url = "/writeups"
[[languages.es.menu.main]]
identifier = "Recomendaciones"
name = "Recomendaciones"
url = "/recommendations"

[languages.fr]
baseurl = "https://fr.simeononsecurity.ch"
sitemap = { filename = "sitemap.fr.xml" }
languageName = 'Français'
languageCode = "fr"
weight = 3
title = "simeononsecurity"
subtitle = "CyberSécurité, Automatisation, Crypto"
description = "Restez en avance dans la cybersécurité. Découvrez les dernières tendances et les meilleures pratiques en matière de confidentialité, de sécurité et de technologie sur SimeonOnSecurity.ch. Ressource essentielle pour tous."
keywords = "sécurité, confidentialité, automatisation, cybersécurité, technologie de l'information, cryptomonnaie, blog, durcissement, conformité, programmation, devops, PowerShell, C sharp, Ansible, conteneurs Docker, Windows, DoD et DISA STIGs, home labs, solutions d'entreprise, Python, Windows 10"
copyright = "SimeonOnSecurity"
menuMore = "Afficher plus"
writtenBy = "Écrit par"
readMore = "En savoir plus"
readOtherPosts = "Lire d'autres articles"
newerPosts = "Articles plus récents"
olderPosts = "Articles plus anciens"
minuteReadingTime = "min de lecture"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "Modifié :"

[languages.fr.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.fr.menu]
[[languages.fr.menu.main]]
identifier = "Articles"
name = "Articles"
url = "/articles"
[[languages.fr.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.fr.menu.main]]
identifier = "TIL"
name = "Aujourd'hui J'ai Appris"
url = "/til"
[[languages.fr.menu.main]]
identifier = "Writeups"
name = "Writeups"
url = "/writeups"
[[languages.fr.menu.main]]
identifier = "Recommandations"
name = "Recommandations"
url = "/recommendations"

[languages.hi]
baseurl = "https://hi.simeononsecurity.ch"
sitemap = { filename = "sitemap.hi.xml" }
languageName = 'हिन्दी'
languageCode = "hi"
weight = 4
title = "simeononsecurity"
subtitle = "साइबर सुरक्षा, स्वचालन, क्रिप्टो"
description = "साइबर सुरक्षा में आगे रहें। SimeonOnSecurity.ch पर गोपनीयता, सुरक्षा और तकनीक के नवीनतम रुझानों और सर्वोत्तम अभ्यासों की खोज करें। सभी के लिए एक महत्वपूर्ण संसाधन।"
keywords = "सुरक्षा, गोपनीयता, स्वचालन, साइबर सुरक्षा, सूचना प्रौद्योगिकी, क्रिप्टोकरेंसी, ब्लॉग, हार्डनिंग, अनुमानित करना, पालन करना, प्रोग्रामिंग, डेवओप्स, पावरशेल, सी शार्प, एंसिबल, डॉकर कंटेनर, विंडोज, डीओडी और डिसा स्टिग, होम लैब, उद्यम समाधान, पायथन, विंडोज 10"
copyright = "SimeonOnSecurity"
menuMore = "अधिक दिखाएं"
writtenBy = "लेखक :"
readMore = "अधिक जानें"
readOtherPosts = "अन्य लेख पढ़ें"
newerPosts = "नए लेख"
olderPosts = "पुराने लेख"
minuteReadingTime = "मिनट पढ़ने का समय"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "संशोधित:"

[languages.hi.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.hi.menu]
[[languages.hi.menu.main]]
identifier = "Articles"
name = "लेख"
url = "/articles"
[[languages.hi.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.hi.menu.main]]
identifier = "TIL"
name = "आज मैंने सीखा"
url = "/til"
[[languages.hi.menu.main]]
identifier = "Writeups"
name = "व्राइटअप्स"
url = "/writeups"
[[languages.hi.menu.main]]
identifier = "Recommendations"
name = "सिफारिशें"
url = "/recommendations"

[languages.ar]
baseurl = "https://ar.simeononsecurity.ch"
sitemap = { filename = "sitemap.ar.xml" }
languageName = 'العربية'
languageCode = "ar"
weight = 5
title = "simeononsecurity"
subtitle = "الأمن السيبراني، الإدارة، العملات الرقمية"
description = "ابقى على اطلاع في مجال الأمن السيبراني. استكشف آخر الاتجاهات والممارسات الأمنية والتكنولوجية على SimeonOnSecurity.ch. مورد مهم للجميع."
keywords = "أمن، خصوصية، إدارة، أمن سيبراني، تكنولوجيا المعلومات، العملات الرقمية، مدونة، التصلب، التقدير، الامتثال، البرمجة، ديف أوبس، باور شيل، سي شارب، أنسيبل، دوكر كونتينر، ويندوز، الجريمة الرقمية و التحقيق، المختبر المنزلي، حلول الشركات الناشئة، بايثون، ويندوز 10"
copyright = "SimeonOnSecurity"
menuMore = "المزيد"
writtenBy = "المؤلف:"
readMore = "اقرأ المزيد"
readOtherPosts = "اقرأ المزيد"
newerPosts = "أحدث المقالات"
olderPosts = "المقالات السابقة"
minuteReadingTime = "دقيقة واحدة للقراءة"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "تم التعديل في:"

[languages.ar.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.ar.menu]
[[languages.ar.menu.main]]
identifier = "Articles"
name = "المقالات"
url = "/articles"
[[languages.ar.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.ar.menu.main]]
identifier = "TIL"
name = "ما تعلمته اليوم"
url = "/til"
[[languages.ar.menu.main]]
identifier = "Writeups"
name = "كتابات"
url = "/writeups"
[[languages.ar.menu.main]]
identifier = "Recommendations"
name = "التوصيات"
url = "/recommendations"

[languages.de]
baseurl = "https://de.simeononsecurity.ch"
sitemap = { filename = "sitemap.de.xml" }
languageName = 'Deutsch'
languageCode = "de"
weight = 6
title = "simeononsecurity"
subtitle = "Cybersicherheit, Automatisierung, Kryptowährung"
description = "Bleiben Sie in Sachen Cybersicherheit auf dem neuesten Stand. Entdecken Sie die neuesten Trends und bewährten Praktiken in Bezug auf Datenschutz, Sicherheit und Technologie auf SimeonOnSecurity.ch. Eine unverzichtbare Ressource für alle."
keywords = "Sicherheit, Datenschutz, Automatisierung, Cybersicherheit, Informationstechnologie, Kryptowährung, Blog, Hardening, Compliance, Programmierung, DevOps, PowerShell, C Sharp, Ansible, Docker-Container, Windows, DoD und DISA STIGs, Home Labs, Unternehmenslösungen, Python, Windows 10"
copyright = "SimeonOnSecurity"
menuMore = "Mehr anzeigen"
writtenBy = "Verfasst von"
readMore = "Mehr lesen"
readOtherPosts = "Weitere Artikel lesen"
newerPosts = "Neuere Artikel"
olderPosts = "Ältere Artikel"
minuteReadingTime = "Min. Lesezeit"
dateFormatSingle = "02.01.2006"
dateFormatList = "02.01.2006"
enableRobotsTXT = "true"
# leave empty to disable, enter display text to enable
lastModDisplay = "Geändert:"

[languages.de.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.de.menu]
[[languages.de.menu.main]]
identifier = "Artikel"
name = "Artikel"
url = "/articles"
[[languages.de.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.de.menu.main]]
identifier = "TIL"
name = "Heute gelernt"
url = "/til"
[[languages.de.menu.main]]
identifier = "Writeups"
name = "Writeups"
url = "/writeups"
[[languages.de.menu.main]]
identifier = "Empfehlungen"
name = "Empfehlungen"
url = "/recommendations"
