baseurl = "https://de.simeononsecurity.ch"
defaultContentLanguage = "de"
disableLanguages = [
    'fr',
    'en',
    'es',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]
