baseurl = "https://ro.simeononsecurity.ch"
defaultContentLanguage = "ro"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'zh',
    'pa',
    'pt',
    'ru',
]
[languages]
[languages.ro]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.ro.xml" }]
languageName = "Română"
# languageCode = "ro"
weight = 10
title = "SimeonOnSecurity"
subtitle = "Securitate cibernetică, automatizare și criptografie"
description = "Mențineți-vă la curent cu evoluțiile în domeniul securității informatice. Obțineți cele mai recente știri și cele mai bune practici în ceea ce privește confidențialitatea, securitatea și tehnologia pe SimeonOnSecurity.com. O resursă valoroasă pentru toți."
keywords = "securitate, confidențialitate, automatizare, securitate informatică, tehnologia informației, criptomonede, blog, îmbunătățire continuă, programare, devops, powershell, c sharp, ansible, containere docker, windows, dod și sst, laborator acasă, depanare kernel, python, windows 10"
copyright = "SimeonOnSecurity"
menuMore = "Mai mult"
writtenBy = "Scris de"
readMore = "Citește mai mult"
readOtherPosts = "Citește alte articole"
newerPosts = "Articole mai noi"
olderPosts = "Articole mai vechi"
minuteReadingTime = "timp de citire în minute"
dateFormatSingle = "02.01.2006"
dateFormatList = "02.01.2006"
enableRobotsTXT = "true"
lastModDisplay = "Ultima actualizare:"

[languages.ro.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "https://ro.simeononsecurity.ch"

[languages.ro.menu]
[[languages.ro.menu.main]]
identifier = "Articole"
name = "Articole"
url = "/articles"
[[languages.ro.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.ro.menu.main]]
identifier = "TIL"
name = "Astăzi am învățat"
url = "/til"
[[languages.ro.menu.main]]
identifier = "Scriere"
name = "Scriere"
url = "/writeups"
[[languages.ro.menu.main]]
identifier = "Recomandări"
name = "Recomandări"
url = "/recomendations"
