baseurl = "https://zh.simeononsecurity.ch"
defaultContentLanguage = "zh"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'pa',
    'pt',
    'ru',
]
[languages]
[languages.zh]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.zh.xml" }]
languageName = "中文"
# languageCode = "zh"
weight = 10
title = "SimeonOnSecurity"
subtitle = "网络安全、自动化和加密"
description = "保持对网络安全的发展与更新。在SimeonOnSecurity上获取有关隐私、安全和技术的最新新闻和最佳实践。这是一个对所有人都有价值的资源。"
keywords = "安全，隐私，自动化，网络安全，信息技术，加密货币，博客，持续改进，编程，DevOps，PowerShell，C#，Ansible，Docker容器，Windows，DoD和SST，家庭实验室，核心问题解决，Python，Windows 10"
copyright = "SimeonOnSecurity"
menuMore = "更多"
writtenBy = "作者"
readMore = "阅读更多"
readOtherPosts = "阅读其他文章"
newerPosts = "新一篇文章"
olderPosts = "旧一篇文章"
minuteReadingTime = "分钟阅读时间"
dateFormatSingle = "2006年01月02日"
dateFormatList = "2006年01月02日"
enableRobotsTXT = "true"
lastModDisplay = "最后更新时间："

[languages.zh.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "https://zh.simeononsecurity.ch"

[languages.zh.menu]
[[languages.zh.menu.main]]
identifier = "文章"
name = "文章"
url = "/articles"
[[languages.zh.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.zh.menu.main]]
identifier = "TIL"
name = "今日所学"
url = "/til"
[[languages.zh.menu.main]]
identifier = "写作"
name = "写作"
url = "/writeups"
[[languages.zh.menu.main]]
identifier = "推荐"
name = "推荐"
url = "/recommendations"