[build]
publish = "public"
#command = "hugo --cleanDestinationDir --environment=production -D -F --gc --minify --verbose"
#command = "hugo --environment=production -D -F --gc --minify --verbose"

# If skip_processing = true, all other settings are ignored
[build.processing]
skip_processing = false
[build.processing.css]
bundle = true
minify = true
[build.processing.js]
bundle = true
minify = true
[build.processing.images]
compress = true

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18.16.0"
#NPM_FLAGS = "npm install --save-dev -g -D babel/cli babel/core babel/preset-env browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import fsevents jimp lru-cache @ampproject/toolbox-optimizer"
#NPM_FLAGS = "npm install --save-dev -g -D @babel/cli @babel/core @babel/preset-env babel/babel browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import jimp lru-cache @ampproject/toolbox-optimizer"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "https://simeononsecurity.ch, https://simeononsecurity.com, https://*.simeononsecurity.ch, https://*.simeononsecurity.com"
Cache-Control = "Public, max-age=31536000"
#The `Expect-CT` header is deprecated and will be removed. Chrome requires Certificate Transparency for all publicly trusted certificates issued after April 30, 2018.
#Expect-Ct = "enforce, max-age=2592000, report-uri='https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct'"
#Feature-Policy = "microphone 'none'; geolocation 'none'; accelerometer 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; gyroscope 'none'; magnetometer 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; publickey-credentials-get 'none'; usb 'none'; xr-spatial-tracking 'none'"
Permissions-Policy = "sync-xhr=(self), accelerometer=(), camera=(), display-capture=(), geolocation=(), microphone=(), midi=(), payment=(), usb=(), gyroscope=(), magnetometer=(), screen-wake-lock=(), xr-spatial-tracking=()"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Upgrade-Insecure-Requests = "1"
Referrer-Policy = "strict-origin"
X-DNS-Prefetch-Control = "active"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-Robots-Tag = "index, follow, max-snippet:60, max-image-preview:large"
X-Xss-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'self' https://simeononsecurity.ch https://simeononsecurity.com https://*.simeononsecurity.ch https://*.simeononsecurity.com https://*.cloudfront.net https://ajax.cloudflare.com https://raw.githubusercontent.com 'unsafe-inline' https: data:; script-src 'self' https://simeononsecurity.ch https://simeononsecurity.com https://*.simeononsecurity.ch https://*.simeononsecurity.com https://*.googlesyndication.com https://*.amazon-adsystem.com https://cdnjs.cloudflare.com/ https://*.cloudfront.net https://ajax.cloudflare.com https://raw.githubusercontent.com https://ws-na.amazon-adsystem.com https://www.google-analytics.com/ https://cdn.ampproject.org https://cdn.jsdelivr.net https://*.gstatic.com https://googleads.g.doubleclick.net https://tpc.googlesyndication.com https://googletagservices.com 'unsafe-inline' 'unsafe-eval' https: data:; font-src 'self' data: https: https://fonts.gstatic.com https://*.cloudfront.net https://simeononsecurity.ch https://simeononsecurity.com https://*.simeononsecurity.ch https://*.simeononsecurity.com ; object-src 'none'; img-src 'self' data: https: https://*.cloudfront.net https://raw.githubusercontent.com; frame-src 'self' https: data: https://googleads.g.doubleclick.net https://ws-na.amazon-adsystem.com; upgrade-insecure-requests; frame-ancestors 'none'"
Cross-Origin-Opener-Policy-Report-Only = 'unsafe-none; report-to="default"'
Cross-Origin-Opener-Policy = 'unsafe-none; report-to="default"'
Cross-Origin-Embedder-Policy-Report-Only = 'unsafe-none; report-to="default"'
Cross-Origin-Embedder-Policy = 'unsafe-none; report-to="default"'
Cross-Origin-Resource-Policy = "cross-origin"
Server = "simeononsecurity"
pagespeed = "on"

[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
for = "/img/*"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[headers]]
for = "/*.jpeg"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"


[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.json"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
for = "/*.xml"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
for = "/*.json"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
for = "/*.xml"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
for = "/*.mjs"
[headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.sass"
[headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.scss"
[headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.less"
[headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.wasm"
[headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.pdf"
[headers.values]
Cache-Control = "public, must-revalidate, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.doc"
[headers.values]
Cache-Control = "public, must-revalidate, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/*.xls"
[headers.values]
Cache-Control = "public, must-revalidate, s-max-age=604800, max-age=31536000"

[[headers]]
for = "/audio/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/videos/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/sse/*"
[headers.values]
Cache-Control = "no-store"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*.htm"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
for = "/*.frag"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[redirects]]
from = "/*"
to = "/:splat"
status = 200
force = true
conditions = { Language = ["en"] }

[[redirects]]
from = "/*"
to = "https://ar.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["ar"] }

[[redirects]]
from = "/*"
to = "https://bn.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["bn"] }

[[redirects]]
from = "/*"
to = "https://ca.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["ca"] }

[[redirects]]
from = "/*"
to = "https://de.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["de"] }

[[redirects]]
from = "/*"
to = "https://es.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["es"] }

[[redirects]]
from = "/*"
to = "https://fr.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["fr"] }

[[redirects]]
from = "/*"
to = "https://hi.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["hi"] }

[[redirects]]
from = "/*"
to = "https://it.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["it"] }

[[redirects]]
from = "/*"
to = "https://ja.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["ja"] }

[[redirects]]
from = "/*"
to = "https://nl.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["nl"] }

[[redirects]]
from = "/*"
to = "https://pa.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["pa"] }

[[redirects]]
from = "/*"
to = "https://pl.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["pl"] }

[[redirects]]
from = "/*"
to = "https://pt.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["pt"] }

[[redirects]]
from = "/*"
to = "https://ro.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["ro"] }

[[redirects]]
from = "/*"
to = "https://ru.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["ru"] }

[[redirects]]
from = "/*"
to = "https://zh.simeononsecurity.ch/:splat"
status = 301
conditions = { Language = ["zh"] }

[[redirects]]
from = "/fr/*"
to = "https://fr.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/es/*"
to = "https://es.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/de/*"
to = "https://de.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/hi/*"
to = "https://hi.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/ar/*"
to = "https://ar.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/ca/*"
to = "https://ca.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/it/*"
to = "https://it.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/ja/*"
to = "https://ja.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/nl/*"
to = "https://nl.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/ro/*"
to = "https://ro.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/zh/*"
to = "https://zh.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/pa/*"
to = "https://pa.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/pt/*"
to = "https://pt.simeononsecurity.ch/:splat"
status = 301

[[redirects]]
from = "/ru/*"
to = "https://ru.simeononsecurity.ch/:splat"
status = 301
