[build]
publish = "public"
command = "hugo --cleanDestinationDir -D -E -F --gc --minify --cacheDir /tmp --verbose"

[context.production.environment]
HUGO_VERSION = "0.99.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "16.15.0"
#NPM_FLAGS = "npm install --save-dev -g -D babel/cli babel/core babel/preset-env browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import fsevents jimp lru-cache @ampproject/toolbox-optimizer"
#NPM_FLAGS = "npm install --save-dev -g -D @babel/cli @babel/core @babel/preset-env babel/babel browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import jimp lru-cache @ampproject/toolbox-optimizer"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
  	Access-Control-Allow-Origin = "https://simeononsecurity.ch https://simeononsecurity.com" 
	Cache-Control = "Public, no-transform, max-age=31536000"
	Expect-Ct = "enforce, max-age=300, report-uri='https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct'"
	#Feature-Policy = "microphone 'none'; geolocation 'none'; accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; battery 'none', camera 'none', display-capture 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none; publickey-credentials-get 'none; usb 'none'; vr 'none'; wake-lock 'none'; xr-spatial-tracking 'none'"
	Permissions-Policy = "microphone=(),geolocation=(),vr=(),usb=(),accelerometer=(),display-capture=(),gyroscope=(),magnetometer=(),midi=(),payment=(),sync-xhr=(self)"
	Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
	Upgrade-Insecure-Requests = "1"
	Referrer-Policy	= "no-referrer"
	X-DNS-Prefetch-Control = "off"
	X-Content-Type-Options = "nosniff"
	X-Frame-Options	= "DENY"
	#X-Robots-Tag  = "noindex, nofollow, noarchive, notranslate, nosnippet, unavailable_after: 2020-09-21"
	X-Robots-Tag  = "index, follow, noarchive, notranslate, max-snippet:20, max-image-preview:large"
	X-Xss-Protection = "1; mode=block"
  	Content-Security-Policy = "default-src 'self' https://simeononsecurity.ch https://simeononsecurity.com https://*.cloudfront.net https://ajax.cloudflare.com 'unsafe-inline' https: data:; font-src https://fonts.gstatic.com https://*.cloudfront.net https://simeononsecurity.ch https://simeononsecurity.com; object-src 'none'; img-src 'self' data: https: *; frame-src https: data:; upgrade-insecure-requests; frame-ancestors 'none'"
	Cross-Origin-Embedder-Policy-Report-Only = '(unsafe-none|require-corp); report-to="default"'
	Cross-Origin-Opener-Policy-Report-Only = '(same-origin|same-origin-allow-popups|unsafe-none); report-to="default"'
	Server = "simeononsecurity"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://simeononsecurity.ch"
	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"
	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = [
		"google",
		"yandex"
	]

[[plugins]]
package = "netlify-plugin-image-optim"
