[build]
publish = "public"
command = "hugo --cleanDestinationDir -D -E -F --gc --minify --cacheDir /tmp --verbose"

[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18.14.0"
#NPM_FLAGS = "npm install --save-dev -g -D babel/cli babel/core babel/preset-env browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import fsevents jimp lru-cache @ampproject/toolbox-optimizer"
#NPM_FLAGS = "npm install --save-dev -g -D @babel/cli @babel/core @babel/preset-env babel/babel browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import jimp lru-cache @ampproject/toolbox-optimizer"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
  	Access-Control-Allow-Origin = "https://simeononsecurity.ch" 
	Cache-Control = "Public, no-transform, max-age=31536000"
	#The `Expect-CT` header is deprecated and will be removed. Chrome requires Certificate Transparency for all publicly trusted certificates issued after April 30, 2018.
	#Expect-Ct = "enforce, max-age=2592000, report-uri='https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct'"
	#Feature-Policy = "microphone 'none'; geolocation 'none'; accelerometer 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; gyroscope 'none'; magnetometer 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; publickey-credentials-get 'none'; usb 'none'; xr-spatial-tracking 'none'"
	Permissions-Policy = "sync-xhr=(self), accelerometer=(), camera=(), display-capture=(), geolocation=(), microphone=(), midi=(), payment=(), usb=(), gyroscope=(), magnetometer=(), screen-wake-lock=(), xr-spatial-tracking=()"
	Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
	Upgrade-Insecure-Requests = "1"
	Referrer-Policy	= "strict-origin"
	X-DNS-Prefetch-Control = "off"
	X-Content-Type-Options = "nosniff"
	X-Frame-Options	= "DENY"
	#X-Robots-Tag  = "noindex, nofollow, noarchive, notranslate, nosnippet, unavailable_after: 2020-09-21"
	X-Robots-Tag  = "index, follow, noarchive, notranslate, max-snippet:60, max-image-preview:large"
	X-Xss-Protection = "1; mode=block"
	Content-Security-Policy = "default-src 'self' https://simeononsecurity.ch https://simeononsecurity.com https://*.cloudfront.net https://ajax.cloudflare.com https://raw.githubusercontent.com 'unsafe-inline' https: data:; script-src 'self' https://simeononsecurity.ch https://simeononsecurity.com https://*.cloudfront.net https://ajax.cloudflare.com https://raw.githubusercontent.com https://ws-na.amazon-adsystem.com https://*.googlesyndication.com https://www.google-analytics.com/ https://cdn.ampproject.org https://cdn.jsdelivr.net https://*.gstatic.com https://googleads.g.doubleclick.net https://tpc.googlesyndication.com https://googletagservices.com 'unsafe-inline' https: data:; font-src 'self' data: https: https://fonts.gstatic.com https://*.cloudfront.net https://simeononsecurity.ch https://simeononsecurity.com; object-src 'none'; img-src 'self' data: https: https://raw.githubusercontent.com; frame-src 'self' https: data: https://googleads.g.doubleclick.net https://ws-na.amazon-adsystem.com; upgrade-insecure-requests; frame-ancestors 'none'"
	Cross-Origin-Opener-Policy-Report-Only = 'unsafe-none; report-to="default"'
	Cross-Origin-Opener-Policy = 'unsafe-none; report-to="default"'
	Cross-Origin-Embedder-Policy-Report-Only = 'unsafe-none; report-to="default"'
	Cross-Origin-Embedder-Policy = 'unsafe-none; report-to="default"'
	Cross-Origin-Resource-Policy = "cross-origin"
	Server = "simeononsecurity"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://simeononsecurity.ch"
	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"
	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = [
		"google",
		"yandex"
	]

[[plugins]]
package = "netlify-plugin-image-optim"


[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  # An array of glob patterns for pages on your site
  # Recursive traversal will start from these
  entryPoints = [
    "*.html",
  ]

  # Recurse through all the links and asset references on your page, starting
  # at the entrypoints
  recursive = true

  # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
  # by default. Enabling pretty mode makes the output easier on the eyes.
  pretty = true

  # You can mark some check as skipped, which will block checklinks
  # from ever attempting to execute them.
  # skipPatterns is an array of strings you can match against failing reports
  skipPatterns = []

  # You can mark some check as todo, which will execute the check, but allow failures.
  # todoPatterns is an array of strings you can match against failing reports
  todoPatterns = []

  # Report on all broken links to external pages.
  # Enabling this will make your tests more brittle, since you can't control
  # external pages.
  checkExternal = false

  # Enable to check references to source maps, source map sources etc.
  # Many build tools don't emit working references, so this is disabled by default
  followSourceMaps = false

  [[plugins]]
  package = "netlify-plugin-inline-critical-css"

  # All inputs are optional, so you can omit this section.
  # Defaults are shown below.
  [plugins.inputs]
    # A filter used to target specific files in the publish directory. Be sure to only target HTML files. This option is passed onto the readdirp library, see https://github.com/paulmillr/readdirp#options for more info.
    fileFilter = ["*.html"]

    # A filter used to target or ignore specific directories in the publish directory. This option is passed onto the readdirp library, see https://github.com/paulmillr/readdirp#options for more info.
    directoryFilter = ["!node_modules"]

    # You can refer to `critical`’s documentation: https://github.com/addyosmani/critical for all options below.
    # Whether to remove the inlined styles from any stylesheet referenced in the HTML. Use with caution. Removing the critical CSS per page results in a unique async loaded CSS file for every page, meaning you can’t rely on cache across multiple pages.
    extract = false

    # An array of objects containing `width` and `height` properties to deliver critical CSS for multiple screen resolutions.
    dimensions = [
      { width = 414, height = 896 },
      { width = 1920, height = 1080 }
    ]

	[[plugins]]
package = "netlify-plugin-subfont"

  [plugins.inputs]
  # An array of glob patterns for pages on your site
  # Recursive traversal will start from these
  entryPoints = [
    "*.html",
  ]

  # Follow your links across all pages to optimize the fonts across the entire site
  recursive = true

  # Subfont lets you set CSS font-display value of the optimized subsets
  # See https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
  fontDisplay = "swap"

  # Inline generated CSS @font-face blocks into each page
  # When set to `false` an external CSS file will be created
  inlineCss = true

  # Inline generated font subsets into their respective @font-face blocks
  # When set to `false` external font files will be created
  inlineFonts = true

  # Include fallbacks so the original font will be loaded when dynamic content gets injected at runtime
  # When set to `false` external font files will be created
  fallbacks = true

  [[plugins]]
  package = "netlify-plugin-webmentions"

	[plugins.inputs]

	# The base url of your site (optional, default: main URL set in Netlify)
	baseUrl = "https://simeononsecurity.ch"

	# Path to the feed URL (optional, default: /feed.xml)
	feedPath = "/rss.xml"

	# Maximum number of feed entries to check for mentions (optional, default: 1)
	limit = 1