[build]
# publish = "public"
#command = "hugo --cleanDestinationDir --environment=production -D -F --gc --minify --verbose"
#command = "hugo --environment=production -D -F --gc --minify --verbose"

# If skip_processing = true, all other settings are ignored
[build.processing]
skip_processing = true

# [context.production.environment]
# HUGO_VERSION = "0.136.5"
# HUGO_ENV = "production"
# HUGO_ENABLEGITINFO = "true"
# NODE_VERSION = "18.16.0"
#NPM_FLAGS = "npm install --save-dev -g -D babel/cli babel/core babel/preset-env browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import fsevents jimp lru-cache @ampproject/toolbox-optimizer"
#NPM_FLAGS = "npm install --save-dev -g -D @babel/cli @babel/core @babel/preset-env babel/babel browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import jimp lru-cache @ampproject/toolbox-optimizer"

[[headers]]
for = "/securityheaders*"
[headers.values]
Cache-Control = "Public, max-age=31536000"
Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
for = "/*.xml"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/*.json"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/tags/*"
[headers.values]
X-Robots-Tag = "noindex, follow"

[[headers]]
for = "/admin/*"
[headers.values]
X-Robots-Tag = "noindex, nofollow"

[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
for = "/*.htm"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
for = "/img/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"

[[headers]]
for = "/*.jpeg"
[headers.values]
Access-Control-Allow-Origin = "*"
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Content-Type = "image/jpeg"

[[headers]]
for = "/*.png"
[headers.values]
Access-Control-Allow-Origin = "*"
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Content-Type = "image/png"

[[headers]]
for = "/*.webp"
[headers.values]
Access-Control-Allow-Origin = "*"
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Content-Type = "image/webp"

[[headers]]
for = "/*.ico"
[headers.values]
Access-Control-Allow-Origin = "*"
Cache-Control = "public, max-age=31536000"
Content-Type = "image/x-icon"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, s-maxage=604800, max-age=31536000"
Access-Control-Allow-Origin = "*"
Content-Type = "text/css"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, s-maxage=604800, max-age=31536000"
Access-Control-Allow-Origin = "*"
Content-Type = "application/javascript"

[[headers]]
for = "/*.json"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
Access-Control-Allow-Origin = "*"
Content-Type = "application/json"

[[headers]]
for = "/*.xml"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
Access-Control-Allow-Origin = "*"
Content-Type = "application/xml"

[[headers]]
for = "/*.mjs"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Content-Type = "text/javascript"

[[headers]]
for = "/*.sass"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Content-Type = "text/x-sass"

[[headers]]
for = "/*.scss"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Content-Type = "text/x-scss"

[[headers]]
for = "/*.less"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Content-Type = "text/x-less"

[[headers]]
for = "/*.wasm"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Content-Type = "application/wasm"

[[headers]]
for = "/*.pdf"
[headers.values]
Cache-Control = "public, must-revalidate, s-maxage=604800, max-age=31536000"
Content-Type = "application/pdf"

[[headers]]
for = "/*.doc"
[headers.values]
Cache-Control = "public, must-revalidate, s-maxage=604800, max-age=31536000"
Content-Type = "application/msword"

[[headers]]
for = "/*.xls"
[headers.values]
Cache-Control = "public, must-revalidate, s-maxage=604800, max-age=31536000"
Content-Type = "application/vnd.ms-excel"

[[headers]]
for = "/*.frag"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
Content-Type = "text/plain"

[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Access-Control-Allow-Origin = "*"
Vary = "Origin"

 [[headers]]
for = "/*.woff2"
[headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Access-Control-Allow-Origin = "*"
Vary = "Origin"

[[headers]]
for = "/audio/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/videos/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/sse/*"
[headers.values]
Cache-Control = "no-store"

[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

## HEADERS
[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "https://simeononsecurity.com"
Cache-Control = "Public, s-maxage=604800, max-age=31536000"
Permissions-Policy = "sync-xhr=(self), accelerometer=(), camera=(), display-capture=(), geolocation=(), microphone=(), midi=(), payment=(), usb=(), gyroscope=(), magnetometer=(), screen-wake-lock=(), xr-spatial-tracking=()"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Upgrade-Insecure-Requests = "1"
Referrer-Policy = "strict-origin"
X-DNS-Prefetch-Control = "active"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "sameorigin"
X-Robots-Tag = "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"
X-Xss-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'self' https://simeononsecurity.ch https://simeononsecurity.com https://*.simeononsecurity.ch https://*.simeononsecurity.com https://*.cloudfront.net https://ajax.cloudflare.com https://raw.githubusercontent.com https://nominatim.openstreetmap.org 'unsafe-inline' https: data:; script-src 'self' https://simeononsecurity.ch https://simeononsecurity.com https://*.simeononsecurity.ch https://*.simeononsecurity.com https://*.googlesyndication.com https://*.amazon-adsystem.com https://cdnjs.cloudflare.com/ https://*.cloudfront.net https://ajax.cloudflare.com https://raw.githubusercontent.com https://ws-na.amazon-adsystem.com https://www.google-analytics.com/ https://cdn.ampproject.org https://cdn.jsdelivr.net https://*.gstatic.com https://googleads.g.doubleclick.net https://tpc.googlesyndication.com https://googletagservices.com https://stats.g.doubleclick.net https://utteranc.es https://*.utteranc.es https://pagead2.googlesyndication.com https://go.ezoic.net https://static.cloudflareinsights.com https://resources.infoLinks.com https://www.clarity.ms https://nominatim.openstreetmap.org 'unsafe-inline' 'unsafe-eval' https: data:; font-src 'self' data: https: https://fonts.gstatic.com https://*.cloudfront.net https://simeononsecurity.ch https://simeononsecurity.com https://*.simeononsecurity.ch https://*.simeononsecurity.com ; object-src 'none'; img-src 'self' data: https: https://*.cloudfront.net https://raw.githubusercontent.com; frame-src 'self' https: data: https://googleads.g.doubleclick.net https://stats.g.doubleclick.net https://ws-na.amazon-adsystem.com https://www.youtube.com; upgrade-insecure-requests; frame-ancestors 'none'"
Cross-Origin-Opener-Policy-Report-Only = 'unsafe-none; report-to="default"'
Cross-Origin-Opener-Policy = 'unsafe-none; report-to="default"'
Cross-Origin-Embedder-Policy-Report-Only = 'unsafe-none; report-to="default"'
Cross-Origin-Embedder-Policy = 'unsafe-none; report-to="default"'
Cross-Origin-Resource-Policy = "cross-origin"
Server = "simeononsecurity"
pagespeed = "on"
Vary = "Origin"

# ## REDIRECTS
# [[redirects]]
# from = "/fr/*"
# to = "https://fr.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/es/*"
# to = "https://es.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/de/*"
# to = "https://de.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/hi/*"
# to = "https://hi.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/ar/*"
# to = "https://ar.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/ca/*"
# to = "https://ca.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/it/*"
# to = "https://it.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/ja/*"
# to = "https://ja.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/nl/*"
# to = "https://nl.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/ro/*"
# to = "https://ro.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/zh/*"
# to = "https://zh.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/pa/*"
# to = "https://pa.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/pl/*"
# to = "https://pl.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/pt/*"
# to = "https://pt.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/ru/*"
# to = "https://ru.simeononsecurity.com/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/CyberChef/*"
# to = "https://gchq.github.io/CyberChef/:splat"
# status = 200

# [[redirects]]
# from = "/cyberchef/*"
# to = "https://gchq.github.io/CyberChef/:splat"
# status = 200

# [[redirects]]
# from = "/*"
# to = "https://ar.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["ar"] }

# [[redirects]]
# from = "/*"
# to = "https://bn.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["bn"] }

# [[redirects]]
# from = "/*"
# to = "https://ca.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["ca"] }

# [[redirects]]
# from = "/*"
# to = "https://de.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["de"] }

# [[redirects]]
# from = "/*"
# to = "https://es.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["es"] }

# [[redirects]]
# from = "/*"
# to = "https://fr.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["fr"] }

# [[redirects]]
# from = "/*"
# to = "https://hi.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["hi"] }

# [[redirects]]
# from = "/*"
# to = "https://it.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["it"] }

# [[redirects]]
# from = "/*"
# to = "https://ja.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["ja"] }

# [[redirects]]
# from = "/*"
# to = "https://nl.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["nl"] }

# [[redirects]]
# from = "/*"
# to = "https://pa.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["pa"] }

# [[redirects]]
# from = "/*"
# to = "https://pl.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["pl"] }

# [[redirects]]
# from = "/*"
# to = "https://pt.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["pt"] }

# [[redirects]]
# from = "/*"
# to = "https://ro.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["ro"] }

# [[redirects]]
# from = "/*"
# to = "https://ru.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["ru"] }

# [[redirects]]
# from = "/*"
# to = "https://zh.simeononsecurity.com/:splat"
# status = 301
# conditions = { Language = ["zh"] }
