
baseurl = "https://it.simeononsecurity.ch"
languageCode = "it"
defaultContentLanguage = "it"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]