
baseurl = "https://nl.simeononsecurity.ch"
languageCode = "nl"
defaultContentLanguage = "nl"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
    'pl',
]