# Include the base.toml file
config = "..\\..\\_default\\config.toml"

baseurl = "https://nl.simeononsecurity.ch"
languageCode = "nl"
efaultContentLanguage = "nl"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]

[languages]
[languages.nl]
sitemap = [{ filename = "sitemap.xml" }, { filename = "sitemap.nl.xml" }]
languageName = "Nederlands"
# languageCode = "nl"
weight = 1
title = "SimeonOnSecurity"
subtitle = "Cybersecurity, automatisering en cryptografie"
description = "Blijf op de hoogte van de ontwikkelingen op het gebied van cybersecurity. Ontvang de laatste nieuwtjes en de beste praktijken op het gebied van privacy, beveiliging en technologie op SimeonOnSecurity.ch. Een waardevolle bron voor iedereen."
keywords = "beveiliging, privacy, automatisering, cybersecurity, informatie technologie, cryptocurrency, blog, continuous improvement, programming, devops, powershell, c sharp, ansible, docker containers, windows, dod en sst, home lab, kern probleemoplossing, python, windows 10"
copyright = "SimeonOnSecurity"
menuMore = "Meer"
writtenBy = "Geschreven door"
readMore = "Lees meer"
readOtherPosts = "Lees andere berichten"
newerPosts = "Nieuwere berichten"
olderPosts = "Oudere berichten"
minuteReadingTime = "minuten leestijd"
dateFormatSingle = "02-01-2006"
dateFormatList = "02-01-2006"
enableRobotsTXT = "true"
lastModDisplay = "Laatst bijgewerkt:"

[languages.nl.params.logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[languages.nl.menu]
[[languages.nl.menu.main]]
identifier = "Artikelen"
name = "Artikelen"
url = "/articles"
[[languages.nl.menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "/github"
[[languages.nl.menu.main]]
identifier = "TIL"
name = "Vandaag geleerd"
url = "/til"
[[languages.nl.menu.main]]
identifier = "Schrijven"
name = "Schrijven"
url = "/writeups"
[[languages.nl.menu.main]]
identifier = "Aanbevelingen"
name = "Aanbevelingen"
url = "/recommendations"