baseurl = "https://pl.simeononsecurity.com"
languageCode = "pl"
defaultContentLanguage = "pl"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'ru',
    'pt',
]
