[server]
enableGzip = true

[[server.headers]]
for = "/**.html"
[server.server.headers.values]
Content-Security-Policy = "script-src localhost:1313"
Referrer-Policy = "strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

## HEADERS

[[server.headers]]
# Define which paths this specific [[server.headers]] block will cover.
for = "/*"

[server.headers.values]
Access-Control-Allow-Origin = "*"
#The `Expect-CT` header is deprecated and will be removed. Chrome requires Certificate Transparency for all publicly trusted certificates issued after April 30, 2018.
#Expect-Ct = "enforce, max-age=2592000, report-uri='https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct'"
#Feature-Policy = "microphone 'none'; geolocation 'none'; accelerometer 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; gyroscope 'none'; magnetometer 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; publickey-credentials-get 'none'; usb 'none'; xr-spatial-tracking 'none'"
Permissions-Policy = "sync-xhr=(self), accelerometer=(), camera=(), display-capture=(), geolocation=(), microphone=(), midi=(), payment=(), usb=(), gyroscope=(), magnetometer=(), screen-wake-lock=(), xr-spatial-tracking=()"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Upgrade-Insecure-Requests = "1"
Referrer-Policy = "strict-origin"
X-DNS-Prefetch-Control = "active"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-Robots-Tag = "index, follow, max-snippet:60, max-image-preview:large"
X-Xss-Protection = "1; mode=block"
Server = "simeononsecurity"
Link = '''
  <https://amazon-adsystem.com>; rel=preconnect,
  <https://cdnjs.cloudflare.com>; rel=preconnect,
  <https://cdn.ampproject.org>; rel=preconnect,
  <https://cdn.jsdelivr.net>; rel=preconnect,
  <https://cloudfront.ne>; rel=preconnect,
  <https://fonts.googleapis.com>; rel=preconnect,
  <https://fonts.gstatic.com>; rel=preconnect,
  <https://google-analytics.com>; rel=preconnect,
  <https://googleads.g.doubleclick.net>; rel=preconnect,
  <https://googletagservices.com>; rel=preconnect,
  <https://gstatic.com>; rel=preconnect,
  <https://maxcdn.bootstrapcdn.com>; rel=preconnect,
  <https://pagead1.googlesyndication.com>; rel=preconnect,
  <https://pagead2.googlesyndication.com>; rel=preconnect,
  <https://securepubads.g.doubleclick.net>; rel=preconnect,
  <https://static.cloudflareinsights.com>; rel=preconnect,
  <https://tpc.googlesyndication.com>; rel=preconnect,
  <https://utteranc.es>; rel=preconnect,
  <https://www.clarity.ms>; rel=preconnect,
  <https://www.google-analytics.com>; rel=preconnect,
  <https://www.gstatic.com>; rel=preconnect,
  <https://www.googletagmanager.com>; rel=preconnect,
  <https://z-na.amazon-adsystem.com>; rel=preconnect,
  <https://ws-na.amazon-adsystem.com>; rel=preconnect,
  <https://www.googletagmanager.com/gtag/js?id=G-W3SL745QY6>; rel=preload; as=script,
  <https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4092442123207538>; rel=preload; as=script,
  <https://resources.infolinks.com/js/infolinks_main.js>; rel=preload; as=script,
  <https://cdn.jsdelivr.net/npm/lazyhtml@1.2.3/dist/lazyhtml.min.js>; rel=preload; as=script,
  <https://instant.page/5.2.0>; rel=preload; as=script,
  <https://simeononsecurity.com/manifest.json>; rel=preload; as=fetch; crossorigin=anonymous,
  <https://simeononsecurity.com>; rel=preconnect,
  <https://simeononsecurity.com>; rel=preconnect,
  <https://ar.simeononsecurity.com>; rel=preconnect,
  <https://bn.simeononsecurity.com>; rel=preconnect,
  <https://ca.simeononsecurity.com>; rel=preconnect,
  <https://de.simeononsecurity.com>; rel=preconnect,
  <https://es.simeononsecurity.com>; rel=preconnect,
  <https://fr.simeononsecurity.com>; rel=preconnect,
  <https://hi.simeononsecurity.com>; rel=preconnect,
  <https://it.simeononsecurity.com>; rel=preconnect,
  <https://ja.simeononsecurity.com>; rel=preconnect,
  <https://nl.simeononsecurity.com>; rel=preconnect,
  <https://pa.simeononsecurity.com>; rel=preconnect,
  <https://pl.simeononsecurity.com>; rel=preconnect,
  <https://pt.simeononsecurity.com>; rel=preconnect,
  <https://ro.simeononsecurity.com>; rel=preconnect,
  <https://ru.simeononsecurity.com>; rel=preconnect,
  <https://zh.simeononsecurity.com>; rel=preconnect
'''

[[server.headers]]
for = "/securityheaders*"
[server.headers.values]
Access-Control-Allow-Origin = "*"
Cache-Control = "Public, max-age=31536000"
Content-Security-Policy = "default-src 'self'; connect-src *; font-src *; img-src *; object-src *; script-src *; style-src *; "
Cross-Origin-Resource-Policy = "same-origin"

[[server.headers]]
for = "/*.html"
[server.headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[server.headers]]
for = "/*.htm"
[server.headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[server.headers]]
for = "/img/*"
[server.headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[server.headers]]
for = "/*.jpeg"
[server.headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[server.headers]]
for = "/*.jpg"
[server.headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[server.headers]]
for = "/*.png"
[server.headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[server.headers]]
for = "/*.webp"
[server.headers.values]
Cache-Control = "public, immutable, s-maxage=604800, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[server.headers]]
for = "/*.ico"
[server.headers.values]
Cache-Control = "public, max-age=31536000"
Expires = "{{ currentTime.AddDate 1 0 0 | httpdate }}"

[[server.headers]]
for = "/*.css"
[server.headers.values]
Cache-Control = "public, s-max-age=604800, max-age=31536000"
Access-Control-Allow-Origin = "*"

[[server.headers]]
for = "/*.js"
[server.headers.values]
Cache-Control = "public, s-max-age=604800, max-age=31536000"
Access-Control-Allow-Origin = "*"

[[server.headers]]
for = "/fonts/*"
[server.headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"
Access-Control-Allow-Origin = "*"

[[server.headers]]
for = "/*.json"
[server.headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
Access-Control-Allow-Origin = "*"

[[server.headers]]
for = "/*.xml"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
Access-Control-Allow-Origin = "*"
Content-Type = "application/xml"

[[server.headers]]
for = "/*.mjs"
[server.headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[server.headers]]
for = "/*.sass"
[server.headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[server.headers]]
for = "/*.scss"
[server.headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[server.headers]]
for = "/*.less"
[server.headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[server.headers]]
for = "/*.wasm"
[server.headers.values]
Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[server.headers]]
for = "/*.pdf"
[server.headers.values]
Cache-Control = "public, must-revalidate, s-max-age=604800, max-age=31536000"

[[server.headers]]
for = "/*.doc"
[server.headers.values]
Cache-Control = "public, must-revalidate, s-max-age=604800, max-age=31536000"

[[server.headers]]
for = "/*.xls"
[server.headers.values]
Cache-Control = "public, must-revalidate, s-max-age=604800, max-age=31536000"

[[server.headers]]
for = "/audio/*"
[server.headers.values]
Cache-Control = "public, max-age=31536000"

[[server.headers]]
for = "/videos/*"
[server.headers.values]
Cache-Control = "public, max-age=31536000"

[[server.headers]]
for = "/sse/*"
[server.headers.values]
Cache-Control = "no-store"

[[server.headers]]
for = "/api/*"
[server.headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[server.headers]]
for = "/*.frag"
[server.headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
