
baseurl = "https://pt.simeononsecurity.com"
languageCode = "pt"
defaultContentLanguage = "pt"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'ru',
    'pl',
]
