
baseurl = "https:/ru.simeononsecurity.com"
languageCode = "ru"
defaultContentLanguage = "ru"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'pl',
]