baseurl = "/"
languageCode = "en-us"
title = "Hello Friend"
theme = "hugo-theme-hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "A simple theme for Hugo"
  # "light" or "dark"
  defaultTheme = "dark"

[params.logo]
  logoText = "hello friend"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"

[languages]
  [languages.en]
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
