
baseurl = "https://es.simeononsecurity.com"
languageCode = "es"
defaultContentLanguage = "es"
disableLanguages = [
    'fr',
    'en',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
    'pl',
]