
baseurl = "https://fr.simeononsecurity.com"
languageCode = "fr"
defaultContentLanguage = "fr"
disableLanguages = [
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
    'pl',
]
