
baseurl = "https://zh.simeononsecurity.com"
languageCode = "zh"
defaultContentLanguage = "zh"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'pa',
    'pt',
    'ru',
    'pl',
]
