
baseurl = "https://simeononsecurity.com"
languageCode = "en"
defaultContentLanguage = "en"
disableLanguages = [
    'fr',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
    'pl',
    'pl',
]