
baseurl = "https://simeononsecurity.ch"
languageCode = "en"
defaultContentLanguage = "en"
title = "simeononsecurity"
theme = "soshellofriend"
paginate = 5
canonifyURLs = true
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
relativeURLs = true
enableGitInfo = true
rssLimit = 25
refLinksNotFoundURL = "simeononsecurity.com"
author = "SimeonOnSecurity"

disableLanguages = [
    'fr',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
    'pl',
]

# Suppress deprecated function warnings and raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

[Author]
name = "SimeonOnSecurity"

[permalinks]
  authors = "/authors/:contentbasename/"

[params]
enableMissingTranslationPlaceholders = true

googleAnalytics = "G-"
images = ["/img/banner.png"]
logo = "/img/banner.png"
rssImage = "/img/banner.png"

contentTypeName = "guides"
contentdir = "content"

defaultTheme = "dark"
showMenuItems = 3
showReadingTime = true
rssFullText = false

ampElements = [
  "amp-analytics",
  "amp-social-share",
  "amp-install-serviceworker",
  "amp-iframe",
]

adsensePublisher = ""
facebookSite = ""
twitterSite = "@simeonsecurity"

socialProfiles = [
  "https://github.com/simeononsecurity",
  "https://twitter.com/SimeonSecurity",
  "https://www.youtube.com/@SimeonOnSecurity",
]

github = "https://github.com/simeononsecurity"
twitter = "https://twitter.com/simeonsecurity"
facebook = ""

alternatePageName = "SimeonOnSecurity"
organizationLogo = "/img/banner.png"
organizationName = "SimeonOnSecurity"

publisherName = "SimeonOnSecurity"
publisherLogo = "/img/banner.png"
publisherLogoWidth = 460
publisherLogoHeight = 460

[logo]
logoText = "simeononsecurity"
logoHomeLink = "/"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 1
[sitemap.categories]
priority = 0.5
[sitemap.tags]
priority = 0.5
[sitemap.dates]
priority = 0.3
[sitemap.authors]
priority = 0.3

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^WC_', 'babel']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      enableInlineShortcodes = true

[imaging]
[imaging.exif]
disableDate = true
disableLatLong = true
includeFields = ''

[taxonomies]
  author = 'authors'
  category = 'categories'
  tag = 'tags'
  genre = 'genre'

[outputs]
home = ["HTML", "RSS", "JSON", "fulltext", "imagessitemap", "news", "smartnews", "rssall"]
section = ["HTML"]
page = ["HTML"]
sitemap = [ "Sitemap" ]

[outputFormats.SITEMAP]
    mediatype = "application/xml"
    baseName = "sitemap"

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["xml"]

[outputFormats]
[outputFormats.FEED]
mediatype = "application/rss"
baseName = "feed"

[outputFormats.rssall]
  mediatype = "application/rss"
  rel = "rssall"
  baseName = "rssall"

[outputFormats.fulltext]
  mediatype = "application/rss"
  rel = "fulltext"
  baseName = "fulltext"

[outputFormats.imagessitemap]
  mediaType = 'application/xml'
  rel = 'imagessitemap'
  baseName  = 'imagessitemap'
  noUgly = true 

[outputFormats.news]
  mediaType = 'application/xml'
  rel = 'news'
  baseName  = 'news'
  noUgly = true 

[outputFormats.smartnews]
  mediaType = 'application/rss'
  rel = 'smartnews'
  baseName  = 'smartnews'
  noUgly = true
