# Include the base.toml file
config = "..\\..\\_default\\config.toml"

baseurl = "https://simeononsecurity.ch"
#defaultContentLanguage = "en"
disableLanguages = [
    'fr',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'ro',
    'zh',
    'pa',
    'pt',
    'ru',
]