
baseurl = "https://ro.simeononsecurity.com"
locale = "ro"
defaultContentLanguage = "ro"
disableLanguages = [
    'fr',
    'en',
    'es',
    'de',
    'hi',
    'ar',
    'bn',
    'ca',
    'it',
    'ja',
    'nl',
    'zh',
    'pa',
    'pt',
    'ru',
    'pl',
]