name: Branch Build Hugo - EN

on:
  push:
    paths:
      - "**"
      - "!contents/**" # Exclude the contents folder
      - "contents/**/*.en.md" # Include only *.en.md files within the content folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Print PWD
        run: pwd    

      - name: Build Hugo site
        run: hugo --cleanDestinationDir -D -E -F --gc --minify --verbose --verboseLog --enableGitInfo --config .\config\language\en\config.toml

      - name: Delete non-public folders
        run: |
          find . -type d ! -path './public*' -print0 | xargs -0 rm -rf

      - name: Move files to root
        run: |
          mv ./public/* .
          rm -r ./public

      - name: Commit and push changes
        run: |
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -m "Update website-en branch"
          git push --force --quiet origin HEAD:refs/heads/website-en
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
