name: Branch Build Hugo - EN_alt

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "!contents/**" # Exclude the contents folder
      - "!github/**" # Exclude the .github folder
      - "!git/**" # Exclude the .git folder
      - "config/**"
      - "static/**"
      - "layouts/**"
      - "i18n/**"
      - "themes/**"
      - "contents/**/*.en.md"
      - "index.en.md"
      - "**/index.en.md" # Include only *.en.md files within the content folder
      - "index.en.html"
      - "**/index.en.html"
      - "bump.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.122.0"
          extended: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick perl libimage-exiftool-perl jpegoptim optipng gifsicle pngcrush webp

      - name: Build Hugo site
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-en
          restore-keys: |
            ${{ runner.os }}-hugomod-en

      - name: Build Hugo site
        run: hugo --cleanDestinationDir -D -E -F  --minify --enableGitInfo --cacheDir /tmp/hugo_cache --config /home/runner/work/simeononsecurity.ch/simeon
