name: CloudFlare Worker Deploy Test

on:
  push:
    branches:
      - website-en

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_WORKER_NAME: ${{ secrets.CLOUDFLARE_WORKER_NAME }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  DOMAIN: ${{ secrets.DOMAIN }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download cf-workers-site-template repository
        run: |
          git clone https://github.com/xJonathanLEI/cf-workers-site-template

      - name: Create cf-workers-site-template/public directory
        run: mkdir -p cf-workers-site-template/public

      - name: Move files to cf-workers-site-template/public
        run: |
          find . -maxdepth 1 -not -name "cf-workers-site-template" -exec mv {} cf-workers-site-template/public/ \;

      - name: Publish the site
        run: |
          echo "${CLOUDFLARE_API_TOKEN}" | yarn wrangler config
          yarn run publish

    #   - name: Deploy to Cloudflare Workers
    #     uses: cloudflare/wrangler-action@2.0.0
    #     with:
    #       apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #       workingDirectory: "./public"
