name: Git AV Scan

on:
  push:
    branches:
      - master

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: History AV Scan
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    
    - name: Git AV Scan
      uses: djdefi/gitavscan@main
      with:
        full: '--full'
