name: HTML Validation

on:
  push:
    branches:
      - 'website-en-alt'
      - 'website-en'
      - 'website-it'
      - 'website-nl'
      - 'website-fr'
      - 'website-es'
      - 'website-de'
      - 'website-ja'
      - 'website-pl'
      - 'website-bn'
      - 'website-ru'
      - 'website-pt'
      - 'website-ca'
      - 'website-zh'
      - 'website-pa'
      - 'website-ar'
      - 'website-hi'
      - 'website-ro'
  pull_request:
    branches:
      - 'website-en-alt'
      - 'website-en'
      - 'website-it'
      - 'website-nl'
      - 'website-fr'
      - 'website-es'
      - 'website-de'
      - 'website-ja'
      - 'website-pl'
      - 'website-bn'
      - 'website-ru'
      - 'website-pt'
      - 'website-ca'
      - 'website-zh'
      - 'website-pa'
      - 'website-ar'
      - 'website-hi'
      - 'website-ro'

jobs:
  html_validation_job:
    name: HTML Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .