name: Update Website

on:
  push:
    paths:
      - "**"
      - "!contents/**" # Exclude the contents folder
      - "contents/**/*.en.md" # Include only *.en.md files within the content folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Deploy to Netlify
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.NETLIFY_API_TOKEN }}" \
            -d '{"build": true}' \
            https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_EN_SITE_ID}}/builds
