name: NPM Automation
  uses: bahmutov/npm-install@v1
  on: [push]
  env:
    NODE_ENV: production
  with:
    install-command: npm install --save-dev -g -D eslint-plugin-import@^2.22.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@^4 browserslist clipboard cssnano postcss postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url hugo-extended eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import jimp lru-cache @ampproject/toolbox-optimizer
  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      name: Build and test
      steps:
        - uses: actions/checkout@v2
        - uses: bahmutov/npm-install@v1
        - run: npm t
