name: Push Sitemap to Bing Indexnow and Google Indexing Api

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Schedule to run at 00:00 (midnight) UTC every day

jobs:
  search_urls_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push Bing 1
        uses: 3Alan/search-engines-urls-push@v0.2.3
        with:
          site: ${{ secrets.SITE }}
          sitemap: ${{ secrets.SITEMAP }}
          count: 10
          bing-token: ${{ secrets.BING_TOKEN }}

      - name: Run Search Engines URLs Push action (Google)
        uses: 3Alan/search-engines-urls-push@v0.2.3
        with:
          site: ${{ secrets.SITE }}
          sitemap: ${{ secrets.SITEMAP }}
          count: 150
          google-client-email: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          google-private-key: ${{ secrets.GOOGLE_PRIVATE_KEY }}

      # Mask the sensitive number in the logs
      - name: Mask Sensitive Data
        run: |
          echo "::add-mask::${{ secrets.PROJECT_NUMBER }}"
