name: VirusTotal Scan

on:
  push:
    paths:
      - '**/*.ps1'
      - '**/*.html'

jobs:
  virus_total_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Scan with VirusTotal
      run: |
        for file in $(find . -name "*.ps1" -or -name "*.html"); do
          curl --request POST \
               --url https://www.virustotal.com/api/v3/files \
               --header 'accept: application/json' \
               --header 'content-type: multipart/form-data' \
               --header "x-apikey: ${{ secrets.VT_API_KEY }}" \
               --form file=@$file
        done
